const patterns = {
  "stitch-colorwork": {
    title: "Stitch Colorwork Pattern",
    slug: "stitch-colorwork",
    patternType: "row",
    pdfUrl: "pattern.pdf",
    graphImageUrl: "Stitch Pattern graph.png",
    graphImageAlt: "Stitch Colorwork Pattern graph",
    intro: "Follow the pattern row by row online, or open the PDF if you prefer to print it.",
    howToUseNote: "Guided Mode shows one row at a time. Full Pattern shows every row as a reference.",
    currentRowHelper: "Use Guided Mode to focus on one row at a time while you crochet.",
    graphNoteTitle: "Graph View",
    graphNoteBody: "Use the Open Full Graph button to see the complete chart with your current row highlighted.",
    graphModalLabel: "Full Graph",
    graphModalTitle: "Pattern Chart",
    graphModalCopy: "The highlighted band shows your current row in the graph.",
    colors: {
      Gray: "#c9c3c6",
      Pink: "#f29aa3",
      Black: "#1f1f1f",
      Blue: "#6e88b7",
      Teal: "#9edfe3",
      Navy: "#3f4d7a",
      White: "#ffffff"
    },
   rows: [
    { number: 1, side: "RS", instructions: "Gray x 122", totalStitches: 122 },
    { number: 2, side: "WS", instructions: "Gray x 75, Black x 1, Gray x 46", totalStitches: 122 },
    { number: 3, side: "RS", instructions: "Gray x 45, Black x 3, Gray x 24, Black x 2, Gray x 48", totalStitches: 122 },
    { number: 4, side: "WS", instructions: "Gray x 40, Black x 2, Gray x 5, Black x 3, Gray x 24, Black x 3, Gray x 3, Black x 3, Gray x 18, Black x 9, Gray x 12", totalStitches: 122 },
    { number: 5, side: "RS", instructions: "Gray x 10, Black x 3, Blue x 7, Black x 3, Gray x 16, Black x 9, Gray x 3, Black x 3, Gray x 18, Black x 3, Gray x 4, Black x 3, Gray x 40", totalStitches: 122 },
    { number: 6, side: "WS", instructions: "Gray x 40, Black x 10, Gray x 3, Black x 2, Gray x 13, Black x 14, Gray x 11, Black x 7, Blue x 11, Black x 3, Gray x 8", totalStitches: 122 },
    { number: 7, side: "RS", instructions: "Gray x 7, Black x 2, Blue x 15, Black x 2, Blue x 1, Black x 7, Gray x 5, Black x 2, Blue x 7, Black x 5, Gray x 14, Black x 7, Blue x 4, Black x 4, Gray x 17, Black x 6, Gray x 17", totalStitches: 122 },
    { number: 8, side: "WS", instructions: "Gray x 14, Black x 4, Blue x 3, Black x 9, Gray x 10, Black x 2, Blue x 8, Black x 4, Gray x 16, Black x 2, Blue x 10, Black x 8, Blue x 6, Black x 2, Blue x 16, Black x 2, Gray x 6", totalStitches: 122 },
    { number: 9, side: "RS", instructions: "Gray x 6, Black x 1, Blue x 6, Navy x 4, Blue x 8, Black x 1, Blue x 9, Black x 3, Blue x 12, Black x 1, Gray x 18, Black x 2, Blue x 10, Black x 2, Gray x 3, Black x 7, Blue x 2, Black x 2, Blue x 10, Black x 3, Gray x 12", totalStitches: 122 },
    { number: 10, side: "WS", instructions: "Gray x 11, Black x 2, Blue x 13, Black x 2, Blue x 6, Black x 6, Blue x 11, Black x 2, Gray x 18, Black x 1, Blue x 13, Black x 1, Blue x 10, Black x 1, Blue x 6, Navy x 8, Blue x 4, Black x 2, Gray x 5", totalStitches: 122 },
    { number: 11, side: "RS", instructions: "Gray x 4, Black x 2, Blue x 5, Navy x 9, Blue x 5, Black x 1, Blue x 9, Black x 2, Blue x 13, Black x 20, Blue x 13, Black x 2, Blue x 9, Black x 1, Blue x 15, Black x 1, Gray x 11", totalStitches: 122 },
    { number: 12, side: "WS", instructions: "Gray x 10, Black x 2, Blue x 15, Black x 2, Blue x 7, Black x 2, Blue x 14, Black x 1, Blue x 18, Black x 1, Blue x 14, Black x 2, Blue x 8, Black x 1, Blue x 5, Navy x 10, Blue x 4, Black x 3, Gray x 3", totalStitches: 122 },
    { number: 13, side: "RS", instructions: "Gray x 2, Black x 4, Blue x 4, Navy x 10, Blue x 5, Black x 1, Blue x 8, Black x 1, Blue x 15, Black x 1, Blue x 2, Black x 10, Blue x 6, Black x 1, Blue x 14, Black x 2, Blue x 7, Black x 1, Blue x 6, Navy x 6, Blue x 5, Black x 1, Gray x 10", totalStitches: 122 },
    { number: 14, side: "WS", instructions: "Gray x 9, Black x 2, Blue x 4, Navy x 7, Blue x 6, Black x 1, Blue x 6, Black x 2, Blue x 15, Black x 1, Blue x 3, Black x 5, Teal x 7, Black x 1, Blue x 2, Black x 1, Blue x 15, Black x 2, Blue x 7, Black x 1, Blue x 5, Navy x 10, Blue x 4, Black x 4, Gray x 2", totalStitches: 122 },
    { number: 15, side: "RS", instructions: "Gray x 4, Black x 2, Blue x 4, Navy x 10, Blue x 5, Black x 1, Blue x 7, Black x 2, Blue x 15, Black x 4, Teal x 11, Black x 3, Blue x 1, Black x 1, Blue x 15, Black x 2, Blue x 6, Black x 1, Blue x 5, Navy x 9, Blue x 4, Black x 1, Gray x 9", totalStitches: 122 },
    { number: 16, side: "WS", instructions: "Gray x 8, Black x 2, Blue x 4, Navy x 9, Blue x 5, Black x 1, Blue x 6, Black x 1, Blue x 16, Black x 3, Teal x 15, Black x 2, Blue x 16, Black x 1, Blue x 7, Black x 1, Blue x 6, Navy x 9, Blue x 4, Black x 1, Gray x 5", totalStitches: 122 },
    { number: 17, side: "RS", instructions: "Gray x 5, Black x 1, Blue x 5, Navy x 7, Blue x 7, Black x 1, Blue x 6, Black x 2, Blue x 16, Black x 1, Teal x 17, Black x 2, Blue x 16, Black x 1, Blue x 6, Black x 1, Blue x 5, Navy x 9, Blue x 4, Black x 2, Gray x 8", totalStitches: 122 },
    { number: 18, side: "WS", instructions: "Gray x 7, Black x 3, Blue x 4, Navy x 9, Blue x 5, Black x 1, Blue x 6, Black x 1, Blue x 16, Black x 1, Teal x 18, Black x 1, Blue x 16, Black x 2, Blue x 6, Black x 2, Blue x 7, Navy x 4, Blue x 6, Black x 2, Gray x 5", totalStitches: 122 },
    { number: 19, side: "RS", instructions: "Gray x 4, Black x 4, Blue x 16, Black x 1, Blue x 7, Black x 1, Blue x 17, Black x 1, Teal x 18, Black x 1, Blue x 16, Black x 1, Blue x 6, Black x 1, Blue x 5, Navy x 9, Blue x 4, Black x 3, Gray x 7", totalStitches: 122 },
    { number: 20, side: "WS", instructions: "Gray x 7, Black x 3, Blue x 4, Navy x 9, Blue x 5, Black x 1, Blue x 6, Black x 1, Blue x 16, Black x 1, Teal x 18, Black x 1, Blue x 17, Black x 1, Blue x 7, Black x 2, Blue x 15, Black x 4, Gray x 4", totalStitches: 122 },
    { number: 21, side: "RS", instructions: "Gray x 4, Black x 4, Blue x 15, Black x 1, Blue x 8, Black x 1, Blue x 16, Black x 2, Teal x 18, Black x 1, Blue x 16, Black x 1, Blue x 6, Black x 1, Blue x 6, Navy x 7, Blue x 4, Black x 2, Gray x 9", totalStitches: 122 },
    { number: 22, side: "WS", instructions: "Gray x 10, Black x 1, Blue x 5, Navy x 4, Blue x 7, Black x 2, Blue x 6, Black x 1, Blue x 16, Black x 1, Teal x 19, Black x 1, Blue x 16, Black x 2, Blue x 7, Black x 2, Blue x 13, Black x 2, Gray x 7", totalStitches: 122 },
    { number: 23, side: "RS", instructions: "Gray x 8, Black x 6, Blue x 5, Black x 4, Blue x 8, Black x 2, Blue x 16, Black x 1, Teal x 19, Black x 1, Blue x 16, Black x 1, Blue x 7, Black x 1, Blue x 16, Black x 1, Gray x 10", totalStitches: 122 },
    { number: 24, side: "WS", instructions: "Gray x 9, Black x 2, Blue x 15, Black x 2, Blue x 7, Black x 1, Blue x 16, Black x 1, Teal x 19, Black x 1, Blue x 16, Black x 2, Blue x 11, Black x 11, Gray x 9", totalStitches: 122 },
    { number: 25, side: "RS", instructions: "Gray x 9, Black x 4, Gray x 2, Black x 2, Blue x 14, Black x 1, Blue x 17, Black x 1, Teal x 19, Black x 1, Blue x 16, Black x 1, Blue x 8, Black x 2, Blue x 13, Black x 3, Gray x 9", totalStitches: 122 },
    { number: 26, side: "WS", instructions: "Gray x 9, Black x 5, Blue x 10, Black x 3, Blue x 8, Black x 1, Blue x 16, Black x 1, Teal x 19, Black x 1, Blue x 17, Black x 1, Blue x 14, Black x 1, Gray x 5, Black x 2, Gray x 9", totalStitches: 122 },
    { number: 27, side: "RS", instructions: "Gray x 16, Black x 3, Blue x 12, Black x 1, Blue x 16, Black x 2, Teal x 19, Black x 1, Blue x 16, Black x 1, Blue x 9, Black x 4, Blue x 8, Black x 1, Gray x 13", totalStitches: 122 },
    { number: 28, side: "WS", instructions: "Gray x 13, Black x 2, Blue x 3, Black x 5, Blue x 12, Black x 1, Blue x 16, Black x 1, Teal x 19, Black x 2, Blue x 16, Black x 1, Blue x 11, Black x 2, Gray x 18", totalStitches: 122 },
    { number: 29, side: "RS", instructions: "Gray x 19, Black x 3, Blue x 9, Black x 1, Blue x 16, Black x 1, Teal x 20, Black x 1, Blue x 16, Black x 1, Blue x 16, Black x 1, Blue x 2, Black x 3, Gray x 13", totalStitches: 122 },
    { number: 30, side: "WS", instructions: "Gray x 13, Black x 8, Blue x 14, Black x 1, Blue x 15, Black x 2, Teal x 20, Black x 1, Blue x 16, Black x 1, Blue x 6, Black x 4, Gray x 21", totalStitches: 122 },
    { number: 31, side: "RS", instructions: "Gray x 24, Black x 3, Blue x 4, Black x 1, Blue x 16, Black x 1, Teal x 20, Black x 2, Blue x 15, Black x 1, Blue x 3, Black x 12, Gray x 4, Black x 3, Gray x 13", totalStitches: 122 },
    { number: 32, side: "WS", instructions: "Gray x 31, Black x 1, Blue x 3, Black x 1, Blue x 15, Black x 2, Teal x 20, Black x 1, Blue x 16, Black x 1, Blue x 2, Black x 3, Gray x 26", totalStitches: 122 },
    { number: 33, side: "RS", instructions: "Gray x 28, Black x 1, Blue x 2, Black x 1, Blue x 15, Black x 2, Teal x 21, Black x 1, Blue x 15, Black x 1, Blue x 2, Black x 2, Gray x 31", totalStitches: 122 },
    { number: 34, side: "WS", instructions: "Gray x 31, Black x 2, Blue x 2, Black x 1, Blue x 15, Black x 1, Teal x 21, Black x 2, Blue x 15, Black x 1, Blue x 2, Black x 1, Gray x 28", totalStitches: 122 },
    { number: 35, side: "RS", instructions: "Gray x 28, Black x 1, Blue x 2, Black x 1, Blue x 15, Black x 1, Teal x 22, Black x 1, Blue x 15, Black x 1, Blue x 2, Black x 1, Gray x 32", totalStitches: 122 },
    { number: 36, side: "WS", instructions: "Gray x 32, Black x 1, Blue x 2, Black x 1, Blue x 15, Black x 1, Teal x 22, Black x 1, Blue x 15, Black x 1, Blue x 2, Black x 1, Gray x 28", totalStitches: 122 },
    { number: 37, side: "RS", instructions: "Gray x 28, Black x 2, Blue x 1, Black x 1, Blue x 15, Black x 1, Teal x 22, Black x 1, Blue x 15, Black x 1, Blue x 2, Black x 1, Gray x 32", totalStitches: 122 },
    { number: 38, side: "WS", instructions: "Gray x 32, Black x 2, Blue x 1, Black x 1, Blue x 15, Black x 1, Teal x 22, Black x 1, Blue x 15, Black x 1, Blue x 1, Black x 1, Gray x 29", totalStitches: 122 },
    { number: 39, side: "RS", instructions: "Gray x 29, Black x 1, Blue x 1, Black x 1, Blue x 14, Black x 2, Teal x 22, Black x 1, Blue x 15, Black x 1, Blue x 1, Black x 1, Gray x 33", totalStitches: 122 },
    { number: 40, side: "WS", instructions: "Gray x 33, Black x 1, Blue x 1, Black x 1, Blue x 15, Black x 1, Teal x 22, Black x 2, Blue x 14, Black x 3, Gray x 29", totalStitches: 122 },
    { number: 41, side: "RS", instructions: "Gray x 29, Black x 3, Blue x 14, Black x 1, Teal x 23, Black x 1, Blue x 15, Black x 1, Blue x 1, Black x 1, Gray x 33", totalStitches: 122 },
    { number: 42, side: "WS", instructions: "Gray x 33, Black x 3, Blue x 14, Black x 2, Teal x 23, Black x 1, Blue x 14, Black x 2, Gray x 30", totalStitches: 122 },
    { number: 43, side: "RS", instructions: "Gray x 30, Black x 2, Blue x 14, Black x 1, Teal x 23, Black x 2, Blue x 14, Black x 2, Gray x 34", totalStitches: 122 },
    { number: 44, side: "WS", instructions: "Gray x 34, Black x 2, Blue x 14, Black x 1, Teal x 24, Black x 1, Blue x 13, Black x 3, Gray x 30", totalStitches: 122 },
    { number: 45, side: "RS", instructions: "Gray x 31, Black x 2, Blue x 12, Black x 2, Teal x 24, Black x 1, Blue x 14, Black x 2, Gray x 34", totalStitches: 122 },
    { number: 46, side: "WS", instructions: "Gray x 35, Black x 2, Blue x 13, Black x 1, Teal x 12, Black x 4, Teal x 8, Black x 2, Blue x 12, Black x 2, Gray x 31", totalStitches: 122 },
    { number: 47, side: "RS", instructions: "Gray x 31, Black x 2, Blue x 12, Black x 1, Teal x 9, Black x 1, Teal x 2, Black x 2, Teal x 11, Black x 1, Blue x 13, Black x 2, Gray x 35", totalStitches: 122 },
    { number: 48, side: "WS", instructions: "Gray x 35, Black x 2, Blue x 13, Black x 1, Teal x 11, Black x 1, Teal x 3, Black x 1, Teal x 9, Black x 1, Blue x 12, Black x 1, Gray x 32", totalStitches: 122 },
    { number: 49, side: "RS", instructions: "Gray x 32, Black x 1, Blue x 11, Black x 2, Teal x 9, Black x 1, Teal x 3, Black x 1, Teal x 11, Black x 2, Blue x 12, Black x 1, Gray x 36", totalStitches: 122 },
    { number: 50, side: "WS", instructions: "Gray x 36, Black x 1, Blue x 12, Black x 1, Teal x 12, Black x 1, Teal x 13, Black x 2, Blue x 11, Black x 1, Gray x 32", totalStitches: 122 },
    { number: 51, side: "RS", instructions: "Gray x 32, Black x 1, Blue x 11, Black x 1, Teal x 13, Black x 5, Teal x 9, Black x 1, Blue x 12, Black x 1, Gray x 36", totalStitches: 122 },
    { number: 52, side: "WS", instructions: "Gray x 36, Black x 1, Blue x 12, Black x 1, Teal x 9, Black x 1, Teal x 2, Black x 2, Teal x 13, Black x 1, Blue x 10, Black x 2, Gray x 32", totalStitches: 122 },
    { number: 53, side: "RS", instructions: "Gray x 32, Black x 2, Blue x 9, Black x 2, Teal x 17, Black x 1, Teal x 9, Black x 2, Blue x 10, Black x 2, Gray x 36", totalStitches: 122 },
    { number: 54, side: "WS", instructions: "Gray x 37, Black x 1, Blue x 10, Black x 1, Teal x 10, Black x 1, Teal x 18, Black x 1, Blue x 9, Black x 1, Gray x 33", totalStitches: 122 },
    { number: 55, side: "RS", instructions: "Gray x 33, Black x 1, Blue x 9, Black x 1, Teal x 17, Black x 2, Teal x 10, Black x 1, Blue x 10, Black x 1, Gray x 37", totalStitches: 122 },
    { number: 56, side: "WS", instructions: "Gray x 37, Black x 1, Blue x 9, Black x 2, Teal x 9, Black x 3, Teal x 17, Black x 2, Blue x 8, Black x 1, Gray x 33", totalStitches: 122 },
    { number: 57, side: "RS", instructions: "Gray x 33, Black x 1, Blue x 8, Black x 1, Teal x 20, Black x 1, Teal x 10, Black x 1, Blue x 8, Black x 2, Gray x 37", totalStitches: 122 },
    { number: 58, side: "WS", instructions: "Gray x 38, Black x 1, Blue x 8, Black x 1, Teal x 10, Black x 2, Teal x 19, Black x 2, Blue x 6, Black x 2, Gray x 33", totalStitches: 122 },
    { number: 59, side: "RS", instructions: "Gray x 34, Black x 1, Blue x 6, Black x 1, Teal x 32, Black x 2, Blue x 6, Black x 2, Gray x 38", totalStitches: 122 },
    { number: 60, side: "WS", instructions: "Gray x 39, Black x 1, Blue x 5, Black x 2, Teal x 5, Black x 13, Teal x 15, Black x 2, Blue x 4, Black x 2, Gray x 34", totalStitches: 122 },
    { number: 61, side: "RS", instructions: "Gray x 35, Black x 1, Blue x 3, Black x 2, Teal x 9, Black x 11, Teal x 5, Black x 17, Gray x 39", totalStitches: 122 },
    { number: 62, side: "WS", instructions: "Gray x 38, Black x 6, Teal x 27, Black x 6, Teal x 5, Black x 2, Blue x 1, Black x 2, Gray x 35", totalStitches: 122 },
    { number: 63, side: "RS", instructions: "Gray x 36, Black x 3, Teal x 2, Black x 5, Teal x 36, Black x 5, Gray x 35", totalStitches: 122 },
    { number: 64, side: "WS", instructions: "Gray x 32, Black x 5, Teal x 43, Black x 6, Gray x 36", totalStitches: 122 },
    { number: 65, side: "RS", instructions: "Gray x 35, Black x 3, Teal x 50, Black x 4, Gray x 30", totalStitches: 122 },
    { number: 66, side: "WS", instructions: "Gray x 28, Black x 4, Teal x 15, Black x 23, Teal x 16, Black x 4, Gray x 32", totalStitches: 122 },
    { number: 67, side: "RS", instructions: "Gray x 30, Black x 3, Teal x 15, Black x 5, Blue x 18, Black x 9, Teal x 9, Black x 2, Blue x 2, Black x 2, Gray x 27", totalStitches: 122 },
    { number: 68, side: "WS", instructions: "Gray x 26, Black x 2, Blue x 3, Black x 4, Teal x 1, Black x 9, Blue x 11, Black x 11, Blue x 6, Black x 5, Teal x 13, Black x 3, Gray x 28", totalStitches: 122 },
    { number: 69, side: "RS", instructions: "Gray x 27, Black x 2, Teal x 12, Black x 5, Blue x 7, Black x 3, Navy x 9, Black x 3, Blue x 14, Black x 7, Blue x 6, Black x 2, Gray x 25", totalStitches: 122 },
    { number: 70, side: "WS", instructions: "Gray x 24, Black x 2, Blue x 27, Black x 2, Navy x 13, Black x 2, Blue x 9, Black x 5, Teal x 10, Black x 3, Gray x 25", totalStitches: 122 },
    { number: 71, side: "RS", instructions: "Gray x 24, Black x 2, Blue x 1, Black x 2, Teal x 6, Black x 5, Blue x 11, Black x 2, Navy x 15, Black x 2, Blue x 27, Black x 1, Gray x 24", totalStitches: 122 },
    { number: 72, side: "WS", instructions: "Gray x 24, Black x 1, Blue x 5, Black x 13, Blue x 8, Black x 2, Navy x 17, Black x 2, Blue x 13, Black x 5, Teal x 1, Black x 3, Blue x 3, Black x 2, Gray x 23", totalStitches: 122 },
    { number: 73, side: "RS", instructions: "Gray x 22, Black x 2, Blue x 6, Black x 3, Blue x 16, Black x 2, Navy x 19, Black x 2, Blue x 5, Black x 4, Teal x 10, Black x 3, Blue x 3, Black x 2, Gray x 23", totalStitches: 122 },
    { number: 74, side: "WS", instructions: "Gray x 23, Black x 2, Blue x 2, Black x 2, Teal x 4, Black x 8, Teal x 3, Black x 2, Blue x 3, Black x 2, Navy x 21, Black x 2, Blue x 25, Black x 2, Gray x 21", totalStitches: 122 },
    { number: 75, side: "RS", instructions: "Gray x 21, Black x 1, Blue x 8, Black x 12, Blue x 6, Black x 1, Navy x 23, Black x 1, Blue x 3, Black x 1, Teal x 3, Black x 11, Teal x 3, Black x 2, Blue x 2, Black x 2, Gray x 22", totalStitches: 122 },
    { number: 76, side: "WS", instructions: "Gray x 20, Black x 4, Blue x 1, Black x 2, Teal x 3, Black x 13, Teal x 2, Black x 1, Blue x 2, Black x 2, Navy x 23, Black x 2, Blue x 4, Black x 2, Teal x 10, Black x 3, Blue x 6, Black x 2, Gray x 20", totalStitches: 122 },
    { number: 77, side: "RS", instructions: "Gray x 20, Black x 1, Blue x 5, Black x 3, Teal x 4, Black x 6, Teal x 3, Black x 2, Blue x 3, Black x 1, Navy x 25, Black x 1, Blue x 2, Black x 1, Teal x 1, Black x 15, Teal x 3, Black x 4, Pink x 1, Black x 3, Gray x 18", totalStitches: 122 },
    { number: 78, side: "WS", instructions: "Gray x 17, Black x 2, Pink x 3, Black x 3, Teal x 2, Black x 17, Teal x 1, Black x 1, Blue x 2, Black x 1, Navy x 25, Black x 1, Blue x 2, Black x 2, Teal x 2, Black x 10, Teal x 4, Black x 2, Blue x 4, Black x 1, Gray x 20", totalStitches: 122 },
    { number: 79, side: "RS", instructions: "Gray x 20, Black x 1, Blue x 3, Black x 2, Teal x 3, Black x 13, Teal x 2, Black x 1, Blue x 2, Black x 1, Navy x 25, Black x 1, Blue x 2, Black x 1, Teal x 1, Black x 17, Teal x 2, Black x 3, Pink x 5, Black x 2, Gray x 15", totalStitches: 122 },
    { number: 80, side: "WS", instructions: "Gray x 14, Black x 2, Pink x 6, Black x 2, Teal x 3, Black x 17, Teal x 1, Black x 1, Blue x 2, Black x 1, Navy x 25, Black x 1, Blue x 2, Black x 1, Teal x 1, Black x 15, Teal x 3, Black x 2, Blue x 2, Black x 1, Gray x 20", totalStitches: 122 },
    { number: 81, side: "RS", instructions: "Gray x 19, Black x 2, Blue x 1, Black x 2, Teal x 3, Black x 16, Teal x 1, Black x 1, Blue x 2, Black x 1, Navy x 25, Black x 1, Blue x 2, Black x 1, Teal x 1, Black x 18, Teal x 2, Black x 2, Pink x 7, Black x 2, Gray x 13", totalStitches: 122 },
    { number: 82, side: "WS", instructions: "Gray x 12, Black x 2, Pink x 8, Black x 2, Teal x 2, Black x 18, Teal x 1, Black x 1, Blue x 2, Black x 1, Navy x 25, Black x 1, Blue x 2, Black x 1, Teal x 1, Black x 17, Teal x 3, Black x 1, Blue x 1, Black x 4, Gray x 17", totalStitches: 122 },
    { number: 83, side: "RS", instructions: "Gray x 16, Black x 2, Pink x 2, Black x 3, Teal x 3, Black x 17, Teal x 1, Black x 2, Blue x 1, Black x 1, Navy x 25, Black x 1, Blue x 2, Black x 1, Teal x 1, Black x 18, Teal x 2, Black x 2, Pink x 9, Black x 2, Gray x 11", totalStitches: 122 },
    { number: 84, side: "WS", instructions: "Gray x 10, Black x 2, Pink x 10, Black x 2, Teal x 2, Black x 18, Teal x 1, Black x 1, Blue x 2, Black x 1, Navy x 25, Black x 1, Blue x 1, Black x 1, Teal x 2, Black x 18, Teal x 2, Black x 3, Pink x 3, Black x 2, Gray x 15", totalStitches: 122 },
    { number: 85, side: "RS", instructions: "Gray x 13, Black x 3, Pink x 4, Black x 2, Teal x 3, Black x 19, Teal x 1, Black x 1, Blue x 1, Black x 2, Navy x 22, Black x 3, Blue x 2, Black x 1, Teal x 1, Black x 18, Teal x 2, Black x 1, Pink x 12, Black x 2, Gray x 9", totalStitches: 122 },
    { number: 86, side: "WS", instructions: "Gray x 8, Black x 2, Pink x 13, Black x 1, Teal x 2, Black x 18, Teal x 1, Black x 1, Blue x 4, Black x 2, Navy x 20, Black x 2, Blue x 2, Black x 1, Teal x 1, Black x 20, Teal x 2, Black x 2, Pink x 6, Black x 2, Gray x 12", totalStitches: 122 },
    { number: 87, side: "RS", instructions: "Gray x 11, Black x 2, Pink x 7, Black x 2, Teal x 2, Black x 20, Teal x 1, Black x 1, Blue x 3, Black x 2, Navy x 18, Black x 2, Blue x 5, Black x 1, Teal x 1, Black x 6, White x 3, Black x 9, Teal x 2, Black x 1, Pink x 14, Black x 1, Gray x 8", totalStitches: 122 },
    { number: 88, side: "WS", instructions: "Gray x 7, Black x 2, Pink x 14, Black x 1, Teal x 2, Black x 8, White x 5, Black x 4, Teal x 2, Black x 1, Blue x 6, Black x 4, Navy x 14, Black x 2, Blue x 4, Black x 1, Teal x 1, Black x 20, Teal x 2, Black x 1, Pink x 9, Black x 2, Gray x 10", totalStitches: 122 },
    { number: 89, side: "RS", instructions: "Gray x 10, Black x 1, Pink x 10, Black x 1, Teal x 2, Black x 20, Teal x 1, Black x 1, Blue x 6, Black x 3, Navy x 7, Black x 5, Blue x 9, Black x 1, Teal x 2, Black x 4, White x 6, Black x 7, Teal x 1, Black x 2, Pink x 15, Black x 2, Gray x 6", totalStitches: 122 },
    { number: 90, side: "WS", instructions: "Gray x 6, Black x 1, Pink x 17, Black x 1, Teal x 1, Black x 7, White x 6, Black x 4, Teal x 2, Black x 1, Blue x 13, Black x 9, Blue x 8, Black x 1, Teal x 2, Black x 19, Teal x 2, Black x 1, Pink x 10, Black x 2, Gray x 9", totalStitches: 122 },
    { number: 91, side: "RS", instructions: "Gray x 8, Black x 2, Pink x 11, Black x 2, Teal x 1, Black x 10, White x 4, Black x 5, Teal x 2, Black x 1, Blue x 30, Black x 2, Teal x 2, Black x 3, White x 6, Black x 6, Teal x 2, Black x 1, Pink x 17, Black x 2, Gray x 5", totalStitches: 122 },
    { number: 92, side: "WS", instructions: "Gray x 5, Black x 1, Pink x 18, Black x 2, Teal x 1, Black x 7, White x 4, Black x 4, Teal x 2, Black x 2, Blue x 30, Black x 1, Teal x 2, Black x 4, White x 5, Black x 10, Teal x 1, Black x 1, Pink x 13, Black x 2, Gray x 7", totalStitches: 122 },
    { number: 93, side: "RS", instructions: "Gray x 7, Black x 1, Pink x 14, Black x 1, Teal x 2, Black x 8, White x 6, Black x 4, Teal x 2, Black x 1, Blue x 30, Black x 2, Teal x 3, Black x 5, White x 1, Black x 7, Teal x 2, Black x 2, Pink x 18, Black x 2, Gray x 4", totalStitches: 122 },
    { number: 94, side: "WS", instructions: "Gray x 4, Black x 1, Pink x 18, Black x 3, Teal x 2, Black x 13, Teal x 3, Black x 1, Blue x 31, Black x 1, Teal x 2, Black x 4, White x 6, Black x 8, Teal x 1, Black x 2, Pink x 13, Black x 2, Gray x 7", totalStitches: 122 },
    { number: 95, side: "RS", instructions: "Gray x 8, Black x 2, Pink x 13, Black x 1, Teal x 1, Black x 8, White x 6, Black x 3, Teal x 3, Black x 1, Blue x 31, Black x 1, Teal x 4, Black x 10, Teal x 3, Black x 2, Gray x 1, Black x 1, Pink x 18, Black x 1, Gray x 4", totalStitches: 122 },
    { number: 96, side: "WS", instructions: "Gray x 3, Black x 2, Pink x 17, Black x 2, Gray x 2, Black x 1, Teal x 4, Black x 7, Teal x 6, Black x 1, Blue x 31, Black x 1, Teal x 3, Black x 4, White x 4, Black x 8, Teal x 1, Black x 2, Pink x 13, Black x 1, Gray x 9", totalStitches: 122 },
    { number: 97, side: "RS", instructions: "Gray x 9, Black x 2, Pink x 13, Black x 1, Teal x 2, Black x 14, Teal x 4, Black x 1, Blue x 31, Black x 2, Teal x 16, Black x 1, Gray x 3, Black x 1, Pink x 18, Black x 1, Gray x 3", totalStitches: 122 },
    { number: 98, side: "WS", instructions: "Gray x 3, Black x 1, Pink x 18, Black x 1, Gray x 3, Black x 2, Teal x 15, Black x 2, Blue x 31, Black x 1, Teal x 4, Black x 13, Teal x 3, Black x 1, Pink x 13, Black x 1, Gray x 10", totalStitches: 122 },
    { number: 99, side: "RS", instructions: "Gray x 9, Black x 2, Pink x 13, Black x 2, Teal x 3, Black x 11, Teal x 5, Black x 1, Blue x 32, Black x 1, Teal x 15, Black x 1, Gray x 4, Black x 1, Pink x 18, Black x 1, Gray x 3", totalStitches: 122 },
    { number: 100, side: "WS", instructions: "Gray x 2, Black x 2, Pink x 17, Black x 2, Gray x 4, Black x 2, Teal x 14, Black x 1, Blue x 32, Black x 1, Teal x 7, Black x 7, Teal x 4, Black x 3, Pink x 14, Black x 6, Gray x 4", totalStitches: 122 },
    { number: 101, side: "RS", instructions: "Gray x 3, Black x 2, Pink x 18, Black x 2, Gray x 1, Black x 2, Teal x 17, Black x 1, Blue x 32, Black x 1, Teal x 14, Black x 1, Gray x 6, Black x 1, Pink x 18, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 102, side: "WS", instructions: "Gray x 2, Black x 1, Pink x 18, Black x 1, Gray x 6, Black x 2, Teal x 12, Black x 2, Blue x 32, Black x 1, Teal x 17, Black x 1, Gray x 3, Black x 1, Pink x 19, Black x 1, Gray x 3", totalStitches: 122 },
    { number: 103, side: "RS", instructions: "Gray x 3, Black x 1, Pink x 19, Black x 1, Gray x 3, Black x 2, Teal x 16, Black x 1, Blue x 33, Black x 1, Teal x 11, Black x 2, Gray x 7, Black x 1, Pink x 18, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 104, side: "WS", instructions: "Gray x 1, Black x 2, Pink x 18, Black x 1, Gray x 8, Black x 1, Teal x 10, Black x 2, Blue x 33, Black x 1, Teal x 15, Black x 2, Gray x 4, Black x 1, Pink x 19, Black x 1, Gray x 3", totalStitches: 122 },
    { number: 105, side: "RS", instructions: "Gray x 2, Black x 2, Pink x 19, Black x 1, Gray x 5, Black x 1, Teal x 14, Black x 2, Blue x 33, Navy x 1, Black x 1, Teal x 9, Black x 2, Gray x 8, Black x 1, Pink x 19, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 106, side: "WS", instructions: "Gray x 1, Black x 1, Pink x 18, Black x 2, Gray x 9, Black x 2, Teal x 7, Black x 2, Blue x 35, Black x 1, Teal x 13, Black x 2, Gray x 5, Black x 1, Pink x 20, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 107, side: "RS", instructions: "Gray x 2, Black x 1, Pink x 20, Black x 1, Gray x 6, Black x 2, Teal x 12, Black x 1, Blue x 35, Navy x 1, Black x 1, Teal x 6, Black x 2, Gray x 11, Black x 1, Pink x 18, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 108, side: "WS", instructions: "Gray x 1, Black x 1, Pink x 18, Black x 1, Gray x 12, Black x 2, Teal x 4, Black x 2, Blue x 36, Black x 1, Teal x 11, Black x 2, Gray x 7, Black x 1, Pink x 20, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 109, side: "RS", instructions: "Gray x 2, Black x 1, Pink x 20, Black x 1, Gray x 8, Black x 2, Teal x 9, Black x 2, Blue x 37, Black x 6, Gray x 13, Black x 1, Pink x 18, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 110, side: "WS", instructions: "Gray x 1, Black x 2, Pink x 17, Black x 1, Gray x 14, Black x 3, Blue x 40, Black x 1, Teal x 8, Black x 2, Gray x 9, Black x 1, Pink x 20, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 111, side: "RS", instructions: "Gray x 1, Black x 2, Pink x 20, Black x 1, Gray x 10, Black x 2, Teal x 6, Black x 2, Blue x 41, Black x 1, Gray x 15, Black x 1, Pink x 17, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 112, side: "WS", instructions: "Gray x 1, Black x 2, Pink x 17, Black x 1, Gray x 15, Black x 3, Blue x 40, Black x 2, Teal x 4, Black x 2, Gray x 11, Black x 1, Pink x 21, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 113, side: "RS", instructions: "Gray x 1, Black x 1, Pink x 21, Black x 1, Gray x 12, Black x 6, Blue x 40, Black x 2, Gray x 17, Black x 1, Pink x 18, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 114, side: "WS", instructions: "Gray x 1, Black x 2, Pink x 17, Black x 1, Gray x 18, Black x 2, Blue x 41, Black x 3, Gray x 13, Black x 1, Pink x 21, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 115, side: "RS", instructions: "Gray x 1, Black x 1, Pink x 21, Black x 1, Gray x 15, Black x 2, Blue x 38, Black x 3, Gray x 19, Black x 1, Pink x 17, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 116, side: "WS", instructions: "Gray x 2, Black x 2, Pink x 16, Black x 1, Gray x 21, Black x 3, Blue x 34, Black x 3, Gray x 16, Black x 1, Pink x 21, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 117, side: "RS", instructions: "Gray x 1, Black x 1, Pink x 21, Black x 1, Gray x 18, Black x 3, Blue x 31, Black x 2, Gray x 23, Black x 1, Pink x 13, Black x 4, Gray x 3", totalStitches: 122 },
    { number: 118, side: "WS", instructions: "Gray x 6, Black x 1, Pink x 13, Black x 1, Gray x 24, Black x 4, Blue x 26, Black x 3, Gray x 20, Black x 1, Pink x 21, Black x 1, Gray x 1", totalStitches: 122 },
    { number: 119, side: "RS", instructions: "Gray x 1, Black x 1, Pink x 21, Black x 1, Gray x 22, Black x 4, Blue x 19, Black x 5, Gray x 27, Black x 1, Pink x 13, Black x 1, Gray x 6", totalStitches: 122 },
    { number: 120, side: "WS", instructions: "Gray x 5, Black x 2, Pink x 12, Black x 2, Gray x 27, Black x 4, Blue x 14, Black x 7, Gray x 25, Black x 1, Pink x 20, Black x 2, Gray x 1", totalStitches: 122 },
    { number: 121, side: "RS", instructions: "Gray x 2, Black x 1, Pink x 20, Black x 1, Gray x 30, Black x 5, Blue x 8, Black x 6, Gray x 29, Black x 1, Pink x 13, Black x 2, Gray x 4", totalStitches: 122 },
    { number: 122, side: "WS", instructions: "Gray x 3, Black x 2, Pink x 14, Black x 1, Gray x 33, Black x 2, Blue x 3, Black x 2, Blue x 2, Black x 2, Gray x 34, Black x 1, Pink x 20, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 123, side: "RS", instructions: "Gray x 2, Black x 1, Pink x 20, Black x 1, Gray x 35, Black x 6, Blue x 3, Black x 2, Gray x 32, Black x 1, Pink x 15, Black x 1, Gray x 3", totalStitches: 122 },
    { number: 124, side: "WS", instructions: "Gray x 3, Black x 1, Pink x 15, Black x 1, Gray x 32, Black x 6, Gray x 2, Black x 2, Gray x 35, Black x 2, Pink x 20, Black x 1, Gray x 2", totalStitches: 122 },
    { number: 125, side: "RS", instructions: "Gray x 2, Black x 2, Pink x 20, Black x 1, Gray x 35, Black x 2, Gray x 40, Black x 1, Pink x 14, Black x 2, Gray x 3", totalStitches: 122 },
    { number: 126, side: "WS", instructions: "Gray x 4, Black x 1, Pink x 14, Black x 1, Gray x 77, Black x 1, Pink x 20, Black x 1, Gray x 3", totalStitches: 122 },
    { number: 127, side: "RS", instructions: "Gray x 3, Black x 1, Pink x 20, Black x 1, Gray x 77, Black x 1, Pink x 14, Black x 1, Gray x 4", totalStitches: 122 },
    { number: 128, side: "WS", instructions: "Gray x 4, Black x 2, Pink x 13, Black x 1, Gray x 77, Black x 1, Pink x 20, Black x 1, Gray x 3", totalStitches: 122 },
    { number: 129, side: "RS", instructions: "Gray x 3, Black x 2, Pink x 19, Black x 1, Gray x 77, Black x 1, Pink x 13, Black x 1, Gray x 5", totalStitches: 122 },
    { number: 130, side: "WS", instructions: "Gray x 5, Black x 2, Pink x 12, Black x 1, Gray x 77, Black x 1, Pink x 19, Black x 1, Gray x 4", totalStitches: 122 },
    { number: 131, side: "RS", instructions: "Gray x 4, Black x 2, Pink x 18, Black x 1, Gray x 77, Black x 1, Pink x 12, Black x 1, Gray x 6", totalStitches: 122 },
    { number: 132, side: "WS", instructions: "Gray x 6, Black x 2, Pink x 10, Black x 2, Gray x 77, Black x 1, Pink x 18, Black x 1, Gray x 5", totalStitches: 122 },
    { number: 133, side: "RS", instructions: "Gray x 5, Black x 2, Pink x 17, Black x 1, Gray x 78, Black x 1, Pink x 10, Black x 1, Gray x 7", totalStitches: 122 },
    { number: 134, side: "WS", instructions: "Gray x 7, Black x 3, Pink x 8, Black x 1, Gray x 78, Black x 1, Pink x 17, Black x 1, Gray x 6", totalStitches: 122 },
    { number: 135, side: "RS", instructions: "Gray x 6, Black x 2, Pink x 16, Black x 1, Gray x 78, Black x 1, Pink x 7, Black x 2, Gray x 9", totalStitches: 122 },
    { number: 136, side: "WS", instructions: "Gray x 10, Black x 2, Pink x 5, Black x 2, Gray x 78, Black x 1, Pink x 16, Black x 1, Gray x 7", totalStitches: 122 },
    { number: 137, side: "RS", instructions: "Gray x 7, Black x 2, Pink x 15, Black x 1, Gray x 79, Black x 1, Pink x 2, Black x 4, Gray x 11", totalStitches: 122 },
    { number: 138, side: "WS", instructions: "Gray x 14, Black x 4, Gray x 79, Black x 1, Pink x 14, Black x 2, Gray x 8", totalStitches: 122 },
    { number: 139, side: "RS", instructions: "Gray x 9, Black x 1, Pink x 14, Black x 1, Gray x 97", totalStitches: 122 },
    { number: 140, side: "WS", instructions: "Gray x 97, Black x 1, Pink x 13, Black x 1, Gray x 10", totalStitches: 122 },
    { number: 141, side: "RS", instructions: "Gray x 10, Black x 2, Pink x 12, Black x 1, Gray x 97", totalStitches: 122 },
    { number: 142, side: "WS", instructions: "Gray x 97, Black x 1, Pink x 11, Black x 2, Gray x 11", totalStitches: 122 },
    { number: 143, side: "RS", instructions: "Gray x 12, Black x 3, Pink x 9, Black x 1, Gray x 97", totalStitches: 122 },
    { number: 144, side: "WS", instructions: "Gray x 97, Black x 1, Pink x 8, Black x 2, Gray x 14", totalStitches: 122 },
    { number: 145, side: "RS", instructions: "Gray x 15, Black x 4, Pink x 4, Black x 2, Gray x 97", totalStitches: 122 },
    { number: 146, side: "WS", instructions: "Gray x 98, Black x 6, Gray x 18", totalStitches: 122 },
    { number: 147, side: "RS", instructions: "Gray x 122", totalStitches: 122 }
   ]
  },
  "c2c-sunrise-swatch": {
    title: "C2C Sunrise Swatch",
    slug: "c2c-sunrise-swatch",
    patternType: "c2c",
    intro: "Follow this C2C swatch diagonal by diagonal online and track your progress as you go.",
    howToUseNote:
      "Guided Mode shows one diagonal at a time. Full Pattern shows every diagonal as a reference.",
    currentRowHelper: "Use Guided Mode to focus on one diagonal at a time while you crochet.",
    graphNoteTitle: "Graph View",
    graphNoteBody: "This sample C2C pattern does not include a graph image yet.",
    graphModalLabel: "Full Graph",
    graphModalTitle: "C2C Chart",
    graphModalCopy: "Add a graph image to this pattern later if you want highlighted progress here.",
    stepLabelSingular: "Diagonal",
    stepLabelPlural: "Diagonals",
    totalLabel: "Total blocks",
    directionLabel: "Step note",
    visualLabel: "Visual block chart",
    colors: {
      Cream: "#f5e8d4",
      Peach: "#f2b98e",
      Coral: "#df7c67",
      Rose: "#c85d73",
      Plum: "#7b4c6c"
    },
    steps: [
      {
        number: 1,
        instructions: "Cream x 1",
        totalBlocks: 1,
        turnText: "Increase: make the first C2C block."
      },
      {
        number: 2,
        instructions: "Cream x 1, Peach x 1",
        totalBlocks: 2,
        turnText: "Increase: add one block at the start of the diagonal."
      },
      {
        number: 3,
        instructions: "Cream x 1, Peach x 1, Coral x 1",
        totalBlocks: 3,
        turnText: "Increase: keep building outward."
      },
      {
        number: 4,
        instructions: "Peach x 1, Coral x 2, Rose x 1",
        totalBlocks: 4,
        turnText: "Increase: add one more block and follow the color changes."
      },
      {
        number: 5,
        instructions: "Coral x 1, Rose x 2, Plum x 2",
        totalBlocks: 5,
        turnText: "Even section: maintain the same number of blocks across the diagonal."
      },
      {
        number: 6,
        instructions: "Rose x 1, Plum x 2, Rose x 1",
        totalBlocks: 4,
        turnText: "Decrease: slip stitch into the next block before starting the diagonal."
      },
      {
        number: 7,
        instructions: "Plum x 1, Rose x 1, Coral x 1",
        totalBlocks: 3,
        turnText: "Decrease again and continue matching the color chart."
      },
      {
        number: 8,
        instructions: "Rose x 1, Peach x 1",
        totalBlocks: 2,
        turnText: "Decrease: work two blocks in this diagonal."
      },
      {
        number: 9,
        instructions: "Cream x 1",
        totalBlocks: 1,
        turnText: "Final decrease: finish with the last C2C block."
      }
    ]
  }
};
